# Spam Email Detection Using Naive Bayes Classifier

## First we check whether we are in correct directory or not

In [60]:
!ls

 auto_commit.sh   emails.csv   requirements.txt
 code.ipynb	  README.md   'SPAM Email Dataset.zip'

## Unzip the file out

In [61]:
# !unzip 'SPAM Email Dataset.zip'

## Counting lines to see how many we have to work with

In [62]:
!wc -l emails.csv

5729 emails.csv

## Library importing for python works

In [63]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

## Read the data from the file to program memory

In [64]:
df = pd.read_csv('emails.csv')
df

                                                   text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

## Downloading NLTL - Natural Language Tool Kit for Language processing

In [65]:
# Download necessary NLTK datasets (run these once)
nltk.download('stopwords')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /home/sadman/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/sadman/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

## Preprocessor

In [66]:
# Copied from the internet - learn later
def preprocess_spam(text):
    # 2. Clean: Remove non-letters & lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text).lower()
    
    # 3. Tokenize: Split into words
    words = text.split()
    
    # 4. Lemmatize & Remove Stopwords
    # Converts 'winning' -> 'win', 'prizes' -> 'prize'
    clean_words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
    return " ".join(clean_words)

# Example output:
# "Congratulations! You are winning a free prize!" 
# -> "congratulation win free prize"

## Preprocessing 
1. Making the string lowercase since there is not a single non english words there
2. Counting how large the each mail is
3. Counting how many words are there in each message

In [67]:
data = []
l = len(df)
spam = 0
not_spam = 0

for i in range(0, l):
    mp = {}
    mp["text"]  = preprocess_spam(df["text"][i])
    mp["spam"]  = df["spam"][i]
    mp["words"] = mp["text"].split()
    mp["len"]   = len(df["text"][i])
    mp["wc"] = len(mp["words"])
    data.append(mp)
    spam += mp["spam"]
not_spam = l - spam
print(f"Emails    : {l}")
print(f"Spam      : {spam}")
print(f"Not pam   : {not_spam}")

Emails    : 5728
Spam      : 1368
Not pam   : 4360

In [68]:
data = pd.DataFrame(data)
data

,text,spam,words,len,wc
0,subject naturally irresistible corporate ident...,1,"[subject, naturally, irresistible, corporate, ...",1484,113
1,subject stock trading gunslinger fanny merrill...,1,"[subject, stock, trading, gunslinger, fanny, m...",598,64
2,subject unbelievable new home made easy im wan...,1,"[subject, unbelievable, new, home, made, easy,...",448,40
3,subject color printing special request additio...,1,"[subject, color, printing, special, request, a...",500,46
4,subject money get software cd software compati...,1,"[subject, money, get, software, cd, software, ...",235,19
...,...,...,...,...,...
5723,subject research development charge gpg forwar...,0,"[subject, research, development, charge, gpg, ...",1189,106
5724,subject receipt visit jim thanks invitation vi...,0,"[subject, receipt, visit, jim, thanks, invitat...",1167,119
5725,subject enron case study update wow day super ...,0,"[subject, enron, case, study, update, wow, day...",2131,188
5726,subject interest david please call shirley cre...,0,"[subject, interest, david, please, call, shirl...",1060,97
5727,subject news aurora update aurora version fast...,0,"[subject, news, aurora, update, aurora, versio...",2331,216